version: '3'

services:
  meight:
    build: .
    ports:
      - 8080:8080
    environment:
      GIN_MODE: release
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      REDIS_TTL: 900
      REDIS_DB: 0
      LOG_LEVEL: 0
      SERVER_PORT: 8080
      SERVER: localhost
      REDIS_SERVER: redis
      REDIS_PORT: 6379
      REQUEST_PATH: https://wps.hereapi.com/v8/findsequence2
      API_KEY: Xi-sfj72ReKKh6O1_r0oTz9AUVPx5j84JzMaeRj-mb8
      STARTING_POINT: FintechHouse;38.71814,-9.14552
      CALCULATION_MODE: shortest;truck;traffic:disabled
      DB_USERNAME: meight
      DB_PASSWORD: meight
      DB_PORT: 5432
      DB_NAME: meight
      DB_HOST: postgres
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_healthy
    networks:
      - localnet

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data 
    environment:
      POSTGRES_PASSWORD: meight
      POSTGRES_USER: meight
      POSTGRES_DB: meight
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - localnet
  
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes: 
      - redis:/data
    networks:
      - localnet

# https://stackoverflow.com/questions/75680387/access-bitnami-kafka-docker-container-from-everywhere
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9094:9094'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
    healthcheck:
      test: kafka-topics.sh --bootstrap-server kafka:9092 --topic hc --create --if-not-exists && kafka-topics.sh --bootstrap-server kafka:9092 --topic hc --describe
      interval: 1s
      timeout: 60s
      retries: 60
    networks:
      - localnet

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - localnet

volumes:
  db:
    driver: local
  redis:
    driver: local

networks:
  localnet:
    driver: bridge

