FROM golang:1.21 as base

# Create and change to the app directory.
WORKDIR /app

# Retrieve application dependencies.
# This allows the container build to reuse cached dependencies.
# Expecting to copy go.mod and if present go.sum.
COPY go.* ./
RUN go mod download

# Copy local code to the container image.
COPY . ./

#Load Env variables to run tests
ENV REDIS_SERVER=cache
ENV REDIS_PASSWORD="eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
ENV REDIS_DB=0
ENV REDIS_TTL=900
ENV REDIS_PORT=6379

# Build the binary.
RUN go test ./... 