// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: truck.sql

package entities

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTruck = `-- name: CreateTruck :one
INSERT INTO trucks (
  plate, max_weight
) VALUES (
  $1, $2
)
RETURNING plate, max_weight
`

type CreateTruckParams struct {
	Plate     string
	MaxWeight pgtype.Numeric
}

func (q *Queries) CreateTruck(ctx context.Context, arg CreateTruckParams) (Truck, error) {
	row := q.db.QueryRow(ctx, createTruck, arg.Plate, arg.MaxWeight)
	var i Truck
	err := row.Scan(&i.Plate, &i.MaxWeight)
	return i, err
}
