// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID          int64
	Weight      pgtype.Int4
	Latitude    pgtype.Float8
	Longitude   pgtype.Float8
	Description pgtype.Text
}

type OrderTruck struct {
	Date          string
	OrderID       int64
	TruckPlate    string
	OrderSequence pgtype.Int8
}

type Truck struct {
	Plate     string
	MaxWeight pgtype.Int4
}
