name: Run tests with database
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: turn up the needed containers
      run: docker compose up --build -d postgres redis kafka meight

    - name: wait until kafka is healthy
      run: timeout 60s sh -c 'until docker ps | grep kafka | grep -q healthy; do echo "Waiting for container to be healthy..."; sleep 2; done'

    - name: wait until redis is healthy
      run: timeout 60s sh -c 'until docker ps | grep redis | grep -q healthy; do echo "Waiting for container to be healthy..."; sleep 2; done'

    - name: wait until postgres is healthy
      run: timeout 60s sh -c 'until docker ps | grep postgres | grep -q healthy; do echo "Waiting for container to be healthy..."; sleep 2; done'
          
    - name: run tests
      run: |
        go test ./...